ingeniamc/ingenialink-python

CHANGELOG.md, ingenialink/canopen/register.py, ingenialink/dictionary.py, ingenialink/ethernet/register.py, ingenialink/ipb/register.py, ingenialink/register.py, ingenialink/register_deprecated.py, tests/register/test_canopen_register.py, tests/register/test_ethernet_register.py
Bugs: 
- `enums_count` is never defined when instancing the `Register` class. So, `Register.enums_count=0` even if `enums!=None`. 
- `enum` is a one-element list of dict where the dict is the enum dict. A simple dict should work.
Fix:
- Just define `enums_count=len(enums)` if the user doesn't define the value of `enums_count`
- Convert `enum` type from list of dict to dict.
=> INGK-547 Define enums_count as len(enums) at the Register

ingenialink/canopen/register.py, ingenialink/dictionary.py, ingenialink/enums/register.py, ingenialink/ethernet/register.py, ingenialink/register.py, ingenialink/servo.py, tests/register/test_canopen_register.py, tests/register/test_ethernet_register.py, tests/servo/test_servo.py
This PR:
- Defines a new attribute `Register.address_type`
- Creates a `REG_ADDRESS_TYPE `enum to define the list of possible `address_type`.
- Reads the `address_type `from the xdf file.
- When saving the xcf file, avoids the registers with `address_type=NVM_NONE` and `access != rw`
- Updates tests accordingly
=> INGK-543 - Remove registers with address_type=NVM_NONE or access!=rw from the xcf file

ingenialink/ipb/register.py, tests/canopen/test_canopen_dictionary.py, tests/canopen/test_canopen_register.py, tests/ethernet/test_ethernet_dictionary.py, tests/ethernet/test_ethernet_register.py, tests/test_register.py
This PR improves the tests that do not use communication (with the `no_connection` mark)
Fixes # INGK-559
=> INGK-559 Improve no-communication tests

ingenialink/canopen/network.py, ingenialink/ethercat/servo.py, ingenialink/ipb/register.py, tests/canopen/test_canopen_network.py, tests/canopen/test_canopen_servo.py, tests/config.json, tests/test_servo.py
This PR improves the tests of canopen protocol
Fixes # INGK-561
=> INGK-561 Improve canopen tests

ingenialink/canopen/servo.py, ingenialink/ethernet/servo.py, ingenialink/servo.py
This PR moves some functions of the Servo children to the Servo parent. This simplifies the code and avoids possible bugs when re-defining abstract methods in the children. Only two methods are kept as abstract methods:  `read_raw` and `write_raw`. Those are protocol-dependent methods to write and read byte arrays.
Fixes # INGK-579
=> INGK-579 Avoid repeated code between the Servo children

CHANGELOG.md, ingenialink/servo.py, tests/test_servo.py
If the drive dictionary has no PartNumber, ignore it to create the configuration file.
Fixes # INGK-589
- Connect a servo with a dictionary with no PartNumber
- Save drive configuration
- Check the configuration file was saved correctly
=> Ingk 589 configuration file cannot be saved

CHANGELOG.md, ingenialink/utils/_utils.py
Sometimes, using ethernet, the received data is longer than expected, for instance, 4 bytes are received for a u16 register. We assume this is an FW issue. We could truncate the received data by the expected length to fix this issue at the library level.
Fixes # INGK-591
=> INGK-591 Truncate received data

ingenialink/canopen/network.py
Canopen FW loader always raises the "Could not recover drive" error.
Fixes # INGK-594
=> INGK-594 Fix canopen FW loader

ingenialink/eoe/network.py
There is no need to stop the service. 
The solution is to just perform the following operations the first time the service is started:
- Initialize the network interfaces
-  Create the virtual adapter
-  Initialize the SOEM library
-  Start the forwarder
-  Start the EtherCAT master
Then, each time the service is started again only perform the configuration of the slaves.
=> INGK-541 Implement stop eoe service feature

Jenkinsfile, pyproject.toml, setup.cfg
In this file we can store configuration settings for different tools such as black.
So we can run this command
`python -m black --check ingenialink tests`
Instead of specifying the arguments like this:
`python -m black --check --preview -l 100  ingenialink tests`
=> INGK-604 Add black config to toml

CHANGELOG.md, ingenialink/utils/mcb.py
Fix NACK error code display.
Fixes # INGK-607
- Correctly convert error code from little to big-endian
- Force a NACK error and verify that the error code printed is in the correct format.
- Add the changes at the `[Unreleased]` section of the [CHANGELOG](CHANGELOG.md).
=> INGK-607 Correctly print NACK error code

ingenialink/eoe/network.py
Add an exception if the EoE service fails to initialize on a network interface.
Fixes # INGK-615
- Try to initialize the service on a non-existing network interface exception and verify that the exception is raised.
=> INGK-615 Add exceptions eoe service

ingenialink/eoe/network.py
Currently, to perform a scan, the EoE service must be fully started (virtual adapter, forwarder, etc.). To be compatible with MotionLab, we must be able to perform a scan without having initialized the rest of the components.
Fixes # INGK-616
- Add stop service function.
- Fix command sequence.
- Scan an EoE network several times and verify that the correct number of slaves is found.
=> INGK-616 Isolate scan function from rest components

ingenialink/canopen/register.py, ingenialink/ethernet/register.py, tests/test_register.py
In order to use monitoring/disturbance a mapping of the register address needs to be performed. Create a property in the Register class to get this mapped address.
Fixes # INGK-619
- Added a mapped_address property to EthernetRegister and CanopenRegister
- Added test_register_mapped_address
=> INGK-619 Create mapped address property

docs/api/protocols/eoe/network.rst, docs/api/protocols/eoe_service.rst, ingenialink/eoe/network.py, ingenialink/utils/_utils.py, pytest.ini, tests/eoe/test_eoe_network.py
Add a check in the EoENetwork connection to ensure the IP address is inside the right subnet
Fixes # INGK-620
=> Ingk 620 ecat service does not allow ip out of 192 168 3

ingenialink/servo.py
=> Ingk 621 servo status listener crash in ethernet when receives a timeout

ingenialink/eoe/network.py, tests/eoe/test_eoe_network.py
Close the socket when the garbage collector removes the network. Before this change, if the last drive was disconnected the network became useless and a new network must be created.
Fixes # INGK-635
Please describe the tests that you ran to verify your changes if it applies.
=> INGK-635 Close socket when network is deleted

CHANGELOG.md, ingenialink/servo.py
Recover old Monitoring/Disturbance compatibility
Fixes # INGK-637
=> INGK-637 Recover old Monitoring/Disturbance compatibility

CHANGELOG.md, ingenialink/servo.py
Fix ServoStatusListener for multiaxis
Fixes # INGK-636
=> INGK-636 Fix ServoStatusListener for multiaxis

CHANGELOG.md, ingenialink/ethernet/network.py
This PR changes the way to verify network connection in ethernet. Now a reading is used instead of a ping to avoid conflicts between pings and readings in Capitan.
Fixes INGK-642 
=> INGK-642 Read a register instead of doing a ping (NetStatusListener in Ethernet)

CHANGELOG.md, ingenialink/ethercat/network.py, requirements/requirements.txt, setup.py
Fix the path of the FoE application
This PR changes the way to find the path to the FoE application. It uses inspect module instead of pkg_resources. This is needed to use FoE from ML3.
Fixes # INGK-641
=> INGK-641 Fix the path of the FoE application

ingenialink/__init__.py, ingenialink/servo.py
This PR changes the errors caught in the status listener thread to include NACK and other possible future errors.
Fixes # INGK-651
=> INGK-651 Avoid NACK error to crash the status listener

CHANGELOG.md, ingenialink/eoe/network.py
Please include a summary of the change and which issue is fixed. 
Fixes # INGK-660
Please describe the tests that you ran to verify your changes if it applies.
=> INGK-660 Catch EoE service deinit error when disconnecting the drive

CHANGELOG.md, ingenialink/servo.py
=> INGK-661 Log exceptions in read_coco_moco_register correctly

CHANGELOG.md, ingenialink/utils/_utils.py, tests/test_utils.py
=> INGK-664 In convert_bytes_to_dtype raise an ILValueError if string can't be covert

CHANGELOG.md, ingenialink/eoe/network.py
Wait until EoE starts before connecting the drive. Some times IL tries to connect to the drives too fast, and EoE services can't initialize EoE
Fixes # (INGK-665)
=> INGK-665 Wait EoE starts before connect drive

CHANGELOG.md, ingenialink/__init__.py, ingenialink/ethernet/servo.py
Reread when Ethernet read a wrong address
Fixes # (INGK-668)
=> INGK-668 Reread when ethernet read a wrong address

CHANGELOG.md, ingenialink/servo.py
Set product name correctly if no dictionary file is provided
=> INGK-442 Set product name correctly if no dictionary file is provided

CHANGELOG.md, ingenialink/canopen/register.py, ingenialink/ethernet/register.py, ingenialink/register.py
Delete enums_count parameter in Register class and its subclasses.
=> INGK-512: delete enums count parameter in register constructor

CHANGELOG.md, ingenialink/canopen/network.py, ingenialink/canopen/register.py, ingenialink/canopen/servo.py, tests/canopen/test_canopen_register.py
CanopenRegister constructor is changed, and it has the same order as the EthernetRegister constructor.
=> INGK-675: unify canopen register and ethernet register constructor signature

CHANGELOG.md, ingenialink/canopen/network.py, tests/canopen/test_canopen_network.py
Adapt CANopen's Network status listener to support multi-drives.
Fixes #INGK-315
-  The subscribe_to_status function takes the node ID as argument.
- The start and stop status listener functions no longer require the servo as argument.
- Connect to two CANopen drives, subscribe to their status, and check that the callback functions are notified of the network status changes.
=> INGK-315 Modify status network property in case of multislave

CHANGELOG.md, ingenialink/utils/_utils.py
Exception is raised when trying to write an int to register of float type.
Fixes #INGK-684
- Add int type to accepted types to write to a register of type float.
- Connect to a drive.
- Write an int to a register of type float.
- Check that no exception is raised.
=> INGK-684 Add int type to accepted types

CHANGELOG.md, ingenialink/ethercat/network.py
If the servo status listener is active when disconnecting an EtherCAT (SDOs) servo from the network, a crash occurs.
Fixes #INGK-683
-Stop the servo status listener before disconnecting the servo from the network.
- Connect to an EtherCAT device, activate the network and servo status listeners.
- Disconnect from the drive.
- Check that there is no crash.
=> INGK-683 Crash when disconnecting from drive

CHANGELOG.md, ingenialink/poller.py
This PR adds a try-except to avoid crashes in the Poller due to timeouts.
Fixes # INGK-691 
=> INGK-691 Avoid crashes in Poller due to timeouts

CHANGELOG.md, ingenialink/servo.py
This PR improves the enable and disable methods of the Servo class.
Fixes # INGK-687
=> INGK-687 Improve Servo's enable and disable methods

CHANGELOG.md, ingenialink/canopen/network.py, mypy.ini
When updating a firmware using a ixxat tranceiver may causes VCIErrors from can library. Here these type of errors will be managed.
Fixes # INGK-711
=> bugfix/INGK-711: VCIErrors management

CHANGELOG.md, README.rst, setup.py
This PR deprecates Python 3.6 and 3.7.
Fixes #709
=> INGK-709 Deprecate Python 3.6 and 3.7

ingenialink/poller.py
When polling from a drive, it is not uncommon that a read operation fails (e.g. “Wrong working counter”). This warrants logging a warning, but the exception should be caught in order to prevent the poller thread from terminating (since it’s not a critical error).
Fixes # ([issue](https://novantamotion.atlassian.net/browse/INGK-738))
Connect to a drive with a poller thread and provoke a "Wrong working counter" - error. The thread should not terminate.
A way to easily do this is by using https://github.com/ingeniamc/ingeniajumpstart and connecting to both drives as the program is designed to.
=> INKG-738 fix ILIOError crashing poller threads

ingenialink/virtual/virtual_drive.py
This PR fixes some issues with monitoring of virtual drive to make it usable from ingeniamotion and ingeniawizard.
Fixes # 739
=> INGK-739 Make virtual drive monitoring usable from IW and IM

CHANGELOG.md, docs/api/protocols/ethercat.rst, docs/api/protocols/ethercat/dictionary.rst, docs/api/protocols/ethercat/register.rst, docs/api/protocols/ethercat/servo.rst
Add missing EtherCAT protocol documentation.
Fixes #INGK-769
- Add EtherCAT servo documentation
- Add EtherCAT dictionary documentation
- Add EtherCAT register documentation
- Build docs and check that the missing documentation appears.
=> INGK-769 Add ethercat servo dictionary and register to doc

CHANGELOG.md, Jenkinsfile, ingenialink/ethercat/network.py, ingenialink/ethercat/servo.py, pytest.ini, tests/ethercat/test_ethercat_network.py
If WinPcap is not installed, do not raise an exception on import, but on ethercat network init
Fixes # INGK-766
=> INGK-766 Make pysoem import optional

CHANGELOG.md, ingenialink/virtual/virtual_drive.py, mypy.ini, requirements/requirements.txt, tests/conftest.py, tests/ethernet/test_ethernet_network.py, tests/test_virtual_drive.py
This PR adds emulators of the open-loop and closed-loop plants.
Fixes # INGK-742
=> INGK-742 Emulate control loops in the virtual drive

CHANGELOG.md, Jenkinsfile, README.rst, setup.py, tox.ini
This PR fixes the requirements for Python 3.9 to 3.12. 
Fixes # INGK-713
=> INGK-713 Fix errors with Python 3.9-3.12

CHANGELOG.md, ingenialink/servo.py
Add the possibility to store and restore exclusively subnode 0 values.
Fixes #INGK-798
- Store subnode 0 values.
- Restore subnode 0 values.
**Test 1**
- Set custom values for registers COMMS_CYCLE_TIMEOUT and DRV_PROT_USER_OVER_VOLT.
- Only store the subnode 0 values.
- Perform a power cycle.
- Check that only the COMMS_CYCLE_TIMEOUT value is maintained.
**Test 2**
- Set custom values for registers COMMS_CYCLE_TIMEOUT and DRV_PROT_USER_OVER_VOLT.
- Store all register values.
- Perform a power cycle.
- Only restore the subnode 0 values.
- Perform a power cycle.
- Check that only the DRV_PROT_USER_OVER_VOLT value is maintained.
=> INGK-798 Store parameters and restore parameters always raises an exception when subnode is 0

tests/test_virtual_drive.py, virtual_drive/core.py
This PR allows to write any value in enum register in the virtual drive.
Fixes # INGK-809 
=> INGK-809 Allow any value when writing an enum registe in the virtual drive

CHANGELOG.md, ingenialink/ethercat/servo.py, ingenialink/servo.py, setup.py
Clean ECAT _write_raw and _read_raw functions and update PySOEM library
Fixes # INGK-765
=> Ingk 765 parse wrong work count

CHANGELOG.md, ingenialink/canopen/register.py, ingenialink/dictionary.py, ingenialink/ethernet/register.py, ingenialink/register.py, tests/canopen/test_canopen_register.py, tests/ethercat/test_ethercat_register.py, tests/ethernet/test_ethernet_register.py, tests/test_register.py, tests/virtual/test_virtual_network.py, virtual_drive/core.py
This PR changes how the enums are represented in the Register class.
Please include a summary of the change and which issue is fixed. 
Fixes # INGK-787
=> INGK-787 Use dict to represent enums

tests/resources/Scripts/load_FWs.py
The Jenkins pipeline does not stop when the load FW stage fails.
Fixes # INGK-825
- [] Update docstrings of every function, method or class that change.
- [] Build documentation locally to verify changes.
- [] Add the changes at the `[Unreleased]` section of the [CHANGELOG](CHANGELOG.md).
=> INGK-825 Raise generic exception if firmware loading process fails

ingenialink/ethercat/network.py, tests/ethercat/test_pdo.py
Use the [send_overlap_processdata](https://pysoem.readthedocs.io/en/latest/master.html#pysoem.Master.send_overlap_processdata) function when the PDO mapping is overlapped.
Fixes # INGK-834
- Add the overlapping_io_map attribute to the EthercatNetwork class.
- Use the send_overlap_processdata function when the PDO mapping is overlapped.
=> INGK-834 Fix data processing when PDO mapping is overlapped

CHANGELOG.md, ingenialink/canopen/network.py, ingenialink/eoe/network.py, ingenialink/ethercat/network.py, ingenialink/ethernet/network.py, ingenialink/network.py, tests/canopen/test_canopen_network.py, tests/ethercat/test_ethercat_network.py, tox.ini
This PR adds the `scan_slaves_info` method that performs a scan and returns the product code and revision number of each drive.
Fixes # INGK-823
=> INGK-823 Add scan_slaves_info method

examples/ethercat/process_data_objects.py, ingenialink/ethercat/network.py, ingenialink/ethercat/servo.py, ingenialink/pdo.py, tests/ethercat/test_pdo.py
Don't reset PDO mapping when mapping PDOs
Fixes # INGK-837
- Remove calls to reset_rpdo_mapping and  reset_tpdo_mapping on the set_pdo_map_to_slave method.
- Extend the PDOMap lists with the PDOMaps when calling the set_pdo_map_to_slave method.
- Add the reset_pdo_mapping method.
- Add the remove_rpdo_map method.
- Add the remove_tpdo_map method.
=> INGK-837 Don't reset PDO mapping when mapping PDOs

ingenialink/ethercat/servo.py
Add very little sleep to unlock threads in EtherCAT read/write.
Fixes # INGK-855
=> INGK-855 Add an sleep to unlock threads in SDO read/write

ingenialink/canopen/dictionary.py, ingenialink/ethercat/dictionary.py, ingenialink/ethernet/dictionary.py, ingenialink/servo.py
Add NVM_NONE address type to missing registers to prevent them from being saved to the configuration file.
Fixes # INGK-858
=> INGK-858 Add NVM_NONE address type to missing registers

CHANGELOG.md, ingenialink/ethercat/network.py
Recover the CoE communication after a power cycle. The network status listener must be turned on in order for it to work.
Fixes # INGK-857
- Create the _recover_from_power_cycle method
- Subscribe the  _recover_from_power_cycle method to the network status changes
Steps:
- Connect to a drive (turn on the network status listener).
-  Continuously read a register value
- Turn the power supply off.
- Check that the register is not being read.
- Turn the power supply on.
- Check that the register value is being read.
=> INGK-857 Recover CoE communication after a power cycle

ingenialink/canopen/dictionary.py, ingenialink/canopen/network.py, ingenialink/canopen/register.py, ingenialink/dictionary.py, ingenialink/enums/register.py, ingenialink/ethercat/dictionary.py, ingenialink/ethercat/register.py, ingenialink/ethernet/dictionary.py, ingenialink/ethernet/register.py, ingenialink/pdo.py, ingenialink/register.py, tests/canopen/test_canopen_register.py, tests/ethercat/test_ethercat_dictionary_v3.py, tests/ethercat/test_pdo.py, tests/resources/test_dict_ecat_eoe_v3.0.xdf
Support cyclic TXRX in dictionary v 3
Fixes # INGK-861
- Create an enum for the register cyclic attribute.
- Add cyclic TXRX as an accepted cyclic type in the PDOMapItem class.
I added a new register with cyclic type TXRX to the EtherCAT V3 example dictionary, updated the necessary tests, and checked that all the tests passed.
=> INGK-861 Support cyclic TXRX in dictionary v 3

tests/test_register.py, virtual_drive/resources/virtual_drive.xdf
In this PR the TEST_BOOLEAN is removed from the virtual drive dictionary and is added manually in the tests.
Fixes # INGK-864
=> INGK-864 Add TEST_BOOLEAN register manually

CHANGELOG.md, ingenialink/pdo.py, tests/ethercat/test_pdo.py
Set the RPDOMap values by byte string. 
Fixes # INGK-873
=> INGK-873 Set the RPDOMap values by byte string

CHANGELOG.md, ingenialink/__init__.py, ingenialink/ethercat/network.py
This PR fixes the bug when there are spaces in the path to FoE binary in Windows.
Fixes # INGK-874 
=> INGK-874 Fix FoE when there are blank spaces in the bin path

CHANGELOG.md, ingenialink/canopen/network.py
Autoscan with IXXAT transciever connected raises an exception
Fixes # INGK-882
- Use the IXXAT CAN-FD implementation when scanning for drives.
- Using an IXXAT transceiver scan for drives.
- Check that no unhandled exception occurs.
=> INGK-882 Autoscan with ixxat transciever connected raises an exception

CHANGELOG.md, virtual_drive/core.py
This PR fixes the issue when connecting the virtual drive using an EVE canopen dictionary.
Fixes # INGK-888
=> INGK-888 Fix virtual drive with a dictionary of an EVE canopen

ingenialink/ethernet/network.py
Make sure to close the firmware file in case an exception occurs.
Fixes # INGK-667
- Use a context manager for opening the firmware file.
- Use a context manager for the FTP connection.
- Connect to an EVE-NET-C using ML3
- Load a firmware file using the FTP Bootloader
- Check that the firmware is loaded successfully.
=> INGK-667 Use context manager to close firmware file

tests/ethercat/test_ethercat_network.py
This PR fixes the ethercat tests.
Fixes # INGK-770
=> INGK-770 Fix ethercat tests

CHANGELOG.md, docs/examples/communication.rst, examples/ethercat/ecat_connection.py
Add EtherCAT connection example script
Fixes # INGK-868
- Add an example connection script.
- Run the script and check that the firmware version can be read correctly.
=> INGK-868 Add EtherCAT connection example script

ingenialink/servo.py, ingenialink/utils/_utils.py, tests/test_servo.py
=> INGK-910 Fix get_drive_identification method

ingenialink/ethercat/network.py
Add PREOP + ERROR state.
Fixes # INGK-916
- Add PREOP + ERROR state
=> INGK-916 Add PREOP + ERROR state

tests/ethercat/test_pdo.py
Fix the start_stop_pdo test.
Fixes # INGK-839
- Use the operation mode display register for the TxPDO
- Run the pytest test.
- Check that it is successful.
=> INGK-839 Use the operation mode display register for the TxPDO

ingenialink/canopen/network.py
Update the deprecated CAN bus argument.
Fixes # INGK-905
- Change the bus argument from _bustype_ to _interface_
- Run the CANopen pytest tests.
- Check that the tests pass.
- Check that the DeprecationWarning message is no longer shown.
=> INGK-905 Update the CANopen bustype argument

CHANGELOG.md, ingenialink/ethercat/servo.py
Clear the SDO error after the store parameters operation.
Fixes # INGK-444
- Check the status of the drive to clear the SDO error
The error only happens with EVE-NET-E drives.
- Read/write a register after storing the parameters.
- Check that the read/write operation is successful.
=> INGK-444 Clear the SDO Error after the store parameters

CHANGELOG.md, ingenialink/eoe/network.py
Increase the socket timeout upon the EoE service initialization
Fixes # INGK-653
- Set the EOE_GATEWAY_STATE_CHANGE_TIMEOUT during the EoE service initialization.
Setup:
- 1 EVE-XCR-E
- 1 CAP-NET-E (in boot mode)
- Daisy chain connection
Test 1:
- Connect to the EVE-XCR-E.
- Read a register.
- Check that no error occurs.
Test 2:
- Perform a network scan.
- Check that no error occurs.
Please describe the tests that you ran to verify your changes if it applies.
=> INGK-653 Increase the socket timeout upon the EoE service initialization

CHANGELOG.md, ingenialink/eoe/network.py
Recover the EoE connection after a power cycle
Fixes # INGK-639
- After a disconnection, restart the EoE service until communication the slaves is re-established.
- Connect to a drive via the EoE Network.
- Perform a power cycle
- Check that the connection is recovered.
=> INGK-639 Reconnection is not supported when using new soem service

CHANGELOG.md, ingenialink/canopen/network.py, tests/canopen/test_canopen_network.py
Check the available CAN devices upon scanning.
- Raise an exception upon scanning if a transceiver is not connected or its driver is not installed.
- Try to connect to a CAN device with a transceiver that is not installed.
- Check that an exception is raised.
=> INGK-386 Check for the available CAN devices

CHANGELOG.md, ingenialink/ethercat/network.py
If a drive cannot reach PreOp an exception is raised and the connection is considered unsuccessful. If the servo status listener was active, it remained active after the failed connection.
Fixes # INGK-928
- Stop the servo status listener if the drive cannot reach PreOp.
- Try to connect to a drive (in ERR INIT state) with the servo status listener flag set to True.
- An ILStateError exception is raised.
- Check that the servo status listener is stopped.
=> INGK-928 Disable the servo status listener if the slave cannot reach PreOp state

ingenialink/ethercat/network.py, tests/config.json
Correctly calculate the expected working counter for the process data.
Fixes # INGK-933
- Update the expected process data working counter.
- Connect to an EtherCAT drive (with a EOLT slave tool attached)
- Check that the drive can reach the Op state.
=> INGK-933 Correct expected working counter calculation

CHANGELOG.md, ingenialink/ethernet/servo.py
Attempt a retry after an Ethernet communication timeout.
Fixes # IINGK-914
- Add a retry after a communication timeout
- Continuously read/write registers while pinging the servo drive.
- Check that the communication can be maintained.
=> INGK-914 Add a retry after a communication timeout

CHANGELOG.md, ingenialink/ethercat/servo.py, tests/ethercat/test_eeprom.py
Add methods to read and write to the ESC EEPROM.
Fixes # INGK-893
- Add the read_eeprom method.
- Add the write_eeprom method.
=> INGK-893 Recover EEPROM write functionality for manufacturing

ingenialink/canopen/network.py
Reload the Kvaser lib to refresh the connected transceivers.
Fixes # INGK-929
- Added the _get_available_kvaser_devices method
- Added the _reload_kvaser_lib method
- Install the Kvaser driver
- Connect a Kvaser transceiver
- In a loop:
- Call the get_available_devices
- The transceiver appears as available
- Disconnect the transceiver
- Call the get_available_devices
- No transceiver appears as available.
=> INGK-929 Reload the Kvaser lib to refresh the connected transceivers

setup.py
Allow NumPy versions higher than 1.26.0.
Fixes # INGK-936
- Update setup.py
- Create a virtual environment.
- Install NumPy 1.26.4.
- Install ingenialink.
- Check that there are no conflicts between the requirements.
=> INGK-936 Fix numpy requirement

CHANGELOG.md, ingenialink/servo.py, tests/resources/test_config_file.xcf, tests/test_servo.py
Add a strict mode to the load configuration method. If set, any exception that occurs during the loading configuration process will be raised.
Fixes # INGK-904
- Add the strict flag.
- Code improvement.
=> INGK-904 Load config always returns done

CHANGELOG.md, ingenialink/pdo.py, tests/ethercat/test_pdo.py
Enable working with FSoE PDOs and regular PDOs at the same time.
Fixes # INGK-944
- Allow more than one PDOMap.
- Fix PDO Map register index size.
- Fix TxPDO data slicing.
- Run the [FSoE example](https://github.com/ingeniamc/ingeniamotion/blob/0.8.2/examples/safety_torque_off.py) alongside regular PDOs.
- Check that both PDOs work as expected.
=> INGK-944 Start PDOs with FSoE and custom PDOs

ingenialink/ethernet/register.py, tests/test_register.py
Fix mapped address for subnode 0.
Fixes # INGK-945
- Fix mapped address for subnode 0.
- Mapped a subnode 0 register.
- Check that no error occurs.
=> INGK-945 Fix mapped address for subnode 0

.coveragerc, Jenkinsfile, tox.ini
We decided to not run all the python versions on development branches to reduce pipeline time.
Running the oldest version and newest version is significant enough, and if something is really broken on intermediate releases it will be detected quickly on develop, release and master branches.
Also I've parallelized ethercat and canopen tests to further reduce build time.
Initial reference - 1h 41min 
http://jenkins.ingenia/job/Novanta%20Motion%20-%20Ingenia%20-%20Git/job/ingenialink-python/job/develop/125/
Now - [PENDING]
http://jenkins.ingenia/job/Novanta%20Motion%20-%20Ingenia%20-%20Git/job/ingenialink-python/view/change-requests/job/PR-459/2/
=> Ingk 948 run tests on development branches with only 1 or 2 python version to reduce time

ingenialink/ethercat/network.py
Subscribe to EMCY messages before any read/write operation.
Fixes # INGK-952
- Subscribe to EMCY messages before creating the servo instance.
=> INGK-952 Subscribe to emcy messages before any read/write operation

CHANGELOG.md, ingenialink/dictionary.py, ingenialink/servo.py, tests/test_dictionary.py, tests/test_servo.py
Add default values to the device description attributes of the Dictionary class.
Fixes # INGK-957
- Set the default values of the firmware version, product code, revision number, and part number to None.
- Update the save configuration method accordingly.
=> INGK-957 If dictionary is wrong show an error instead of crash

CHANGELOG.md, ingenialink/canopen/network.py
Fix multiple drive connections with Kvaser CANopen transceiver.
Fixes # INGK-960
1. Scan slaves
2. Connect to slave A
3. Scan slaves
4. Connect to Slave B
5. Scan slaves
6. Disconnect from A and B
=> INGK-960 Unload kvaser library only in connection teardown

virtual_drive/__init__.py, virtual_drive/core.py, virtual_drive/environment.py, virtual_drive/gpios.py, virtual_drive/signals.py
Implemented inputs functionality in virtual drive to be able to test ingeniamotion functionality correctly:
https://github.com/ingeniamc/ingeniamotion/pull/242 
The code of virtual drive is a bit chaotic and we will organize it in the future. 
For this particular feature I've followed the pattern proposed here:
https://novantamotion.atlassian.net/wiki/x/iAHHMQ
We can discuss and change it in the future if necessary
=> INGM-501 Find alternative to IO_IN_VALUE set in motion_controller fixture

setup.py
Update the python-can library version to 4.4.2.
Fixes # INGK-962
- Update setup.py
- Test ML3 with python-can 4.4.2
- Check that everything works as expected.
=> INGK-962 Update python-can

CHANGELOG.md, ingenialink/ethercat/network.py
Improve CoE reconnection after a disconnection.
Fixes # INGK-978
- Retry to transition the slaves to the PreOp state.
- Only consider a drive as connected when in PreOp state.
- Connect to an EtherCAT drive (enabling the network status listener)
- Continuously read a register and:
1. Turn off the power supply
2. Check that the read fails.
3. Turn on the power supply
4. Check that the read is successful.
5. Repeat the previous steps several times.
=> INGK-978 Improve CoE reconnection after a disconnection

ingenialink/pdo.py
Write pdo map items mapping as bytes
Fixes # INGK-984
=> INGK-984 Write pdo map items mapping as bytes

CHANGELOG.md, ingenialink/canopen/servo.py, ingenialink/servo.py
Exclude the RxPDO and TxPDO related registers from the configuration file of CANopen drives.
Fixes # INGK-980
- Connect to a CANopen drive.
- Generate its configuration file.
- Check that no RxPDO and TxPDO related registers are present in the file.
=> INGK-980 Exclude the PDO related registers from the configuration file

CHANGELOG.md, ingenialink/canopen/network.py, ingenialink/canopen/servo.py, ingenialink/emcy.py, ingenialink/ethercat/network.py, ingenialink/ethercat/servo.py, ingenialink/servo.py, tests/test_emcy.py, tests/test_servo.py
Allow users to subscribe to EMCY messages.
Fixes # INGK-985
- Fix CANopen subscription.
- Add a method to subscribe to EtherCAT emergency messages.
- Connect to CANopen / EtherCAT drive
- Subscribe to emergency messages
- Generate emergency messages
- Check that the callback function receives the emergency messages.
=> INGK-985 Allow users to subscribe to EMCY messages

CHANGELOG.md, ingenialink/canopen/register.py, ingenialink/dictionary.py, tests/canopen/test_canopen_dictionary_v3.py, tests/canopen/test_canopen_register.py, tests/resources/canopen/test_dict_can_v3.0.xdf
Implement register property to mark register as node id dependent
Fixes # INGK-989
=> Ingk 989 implement node id depending registers in xdf v3

tests/test_emcy.py
- Create a separate EMCY test for COCO MOCO drives
=> INGK-993 Create a separate EMCY test for COCO MOCO drives

ingenialink/dictionary.py, ingenialink/emcy.py, ingenialink/servo.py, tests/canopen/test_canopen_dictionary_v2.py, tests/canopen/test_canopen_dictionary_v3.py, tests/eoe/test_eoe_dictionary_v3.py, tests/ethercat/test_ethercat_dictionary_v2.py, tests/ethercat/test_ethercat_dictionary_v3.py, tests/ethernet/test_ethernet_dictionary_v2.py, tests/test_dictionary.py
Use a dataclass to represent a dictionary error.
Fixes # INGK-988
- Create the DictionaryError class.
- Remove the DictionaryErrors class.
- Update tests.
=> INGK-988 Use a dataclass to represent a dictionary error

CHANGELOG.md, ingenialink/canopen/network.py
Please include a summary of the change and which issue is fixed. 
Fixes # INGK-991
- Catch PCAN error on disconnection
- Test with ingeniamotion re-including these [changes](https://github.com/ingeniamc/ingeniamotion/pull/266) 
- Check that the tests are successful.
=> INGK-991 Catch PCAN error on disconnection

tests/test_servo.py, tests/test_utils.py
- Add missing EtherCAT mark.
- Only test utils tests once.
=> INGK-955 Test not being run on EtherCAT

CHANGELOG.md, ingenialink/servo.py
- Remove unnecessary parameter.
=> INGK-633 Status listener callback has an extra none argument

CHANGELOG.md, examples/ethercat/process_data_objects.py, ingenialink/pdo.py, ingenialink/register.py, ingenialink/servo.py, ingenialink/utils/_utils.py, tests/test_register.py, tests/test_utils.py
No major changes to user functionality, the default of bytearray512 is now given in bytes.
Also improved the doc and tests, to have a reference on the PR of the other project.
Fixes VOLCANO-611
=> Volcano 611 in dictionary v 3 default volcano parser and ingenialink parser does not match

.github/pull_request_template.md, tox.ini, virtual_drive/__init__.py, virtual_drive/core.py
- Fix linting errors.
- Update the tox environment to include the virtual_drive folder.
- Update the PR template.
=> INGK-1001 Include formatting and linting on virtual drive

tests/conftest.py, tests/test_register.py, tests/test_servo.py, tests/virtual/test_virtual_network.py
I had problems on running some unrelated tests on the CI for this PR: https://github.com/ingeniamc/ingenialink-python/pull/497
The tests failing did not have anything to do with the ones introduced, just that they used virtual drive.
Apparently some tests had a virtual drive global variable and a weird autouse stop fixture that was explicitly used in some cases. 
The pattern is flawed and I think that some tests left the server open, so depending on the set or order that you run the tests you get a timeout error or not. The first fixture is the responsible to cleanup what has created.
I have created a new fixture that allows to create N virtual drives with the dictionary that you want and adapted the tests that had this use case
=> Move virtual drive fixture

CHANGELOG.md, ingenialink/dictionary.py, ingenialink/servo.py, tests/canopen/test_canopen_dictionary_v3.py, tests/ethercat/test_ethercat_dictionary_v3.py, tests/test_dictionary.py
Add function to read product code and revision number from dictionary quickly
Fixes # INGK-1007
=> INGK-1007 add function to quickly read product code and revision number from dictionary

CHANGELOG.md, ingenialink/canopen/dictionary.py, ingenialink/dictionary.py, ingenialink/ethercat/dictionary.py, ingenialink/ethernet/dictionary.py, ingenialink/virtual/dictionary.py, tests/resources/canopen/test_dict_can.xdf, tests/resources/ethernet/test_dict_eth.xdf, tests/test_dictionary.py
Raise exception if DictionaryV2 does not match interface
Fixes # (INGK-1008)
=> INGK-1008 Raise exception if DictionaryV2 does not match interface

README.rst, setup.py, tox.ini
It was not possible to upload wheels to pypi on master:
It was because the readme was not properly formatted. Fixed on master directly, and adding here a check that verifies that is always ready to be published
Running the command before fixing the readme:
=> Fix readme

CHANGELOG.md, ingenialink/ethercat/servo.py, tests/ethercat/test_pdo.py
Avoid mapping a PDO map twice.
Fixes # INGK-1010
=> INGK-1010 Avoid mapping a PDO map twice

Jenkinsfile
The nightly builds are not being triggered.
Fixes # INGK-1019
- Use regular cron (non-parametrized).
- Schedule a build (on a test branch).
- Check that the build is triggered.
=> INGK-1019 Use regular cron

ingenialink/ethernet/network.py
An ftplib.error_temp exception is raised if the firewall is enabled.
Fixes # INGK-1030
- Catch exception.
- Load firmware with the firewall enabled.
- Check that the exception is caught.
=> INGK-1030 Catch ftp exception

CHANGELOG.md, tests/resources/ethercat/test_dict_ethercat_old_dist.xdf, tests/virtual/test_virtual_network.py, virtual_drive/core.py
Some dictionary products with old disturbance are not compatible with virtual drive.
Fixes #INGK-1031
- Disable Virtual Monitoring and Disturbance for Virtual Drives that have old disturbance.
=> Ingk 1031 virtual drive is not compatible with old disturbance and multiaxis

ingenialink/canopen/servo.py, ingenialink/emcy.py, ingenialink/ethercat/servo.py
Create Canopen and Ethercat childs of EmergencyMessage class to avoid confusion between canopen folder and canopen module
Fixes # INGK-1043
=> INGK-1043 Create EthercatEmergencyMessage and CanopenEmergencyMessage

tests/test_servo.py
The fault reset operation on the EVE-XCR-E sometimes takes longer than the SDO read timeout to complete.
Fixes #INGK-1028
- Create a new test for the EVE-XCR-E exclusively, where the SDO read timeout is increased. 
=> INGK-1028 Analyze ingenialink nightly test failures

tests/ethernet/test_ethernet_network.py
Improve ethernet network status listener tests.
Fixes # INGK-1037
- Implement the net status listener disconnection test.
- Unify the net status listener connection and disconnection tests.
- Improve the unsubscribe from status test.
=> INGK-1037 Improve ethernet network status listener tests

CHANGELOG.md, ingenialink/dictionary.py, tests/canopen/test_canopen_dictionary_v2.py, tests/canopen/test_canopen_dictionary_v3.py, tests/eoe/test_eoe_dictionary_v3.py, tests/ethercat/test_ethercat_dictionary_v2.py, tests/ethercat/test_ethercat_dictionary_v3.py, tests/ethernet/test_ethernet_dictionary_v2.py, tests/resources/canopen/test_dict_can_v3.0.xdf, tests/resources/canopen/test_dict_can_v3.0_axis.xdf, tests/resources/test_dict_ecat_eoe_v3.0.xdf
Added parsing of the canopen item datatype from xdf v3
Fixes VOLCANO-632/INGK-1057
=> Volcano 632 include information of canopen item type on xdfv 3

tests/canopen/test_canopen_network.py, tests/conftest.py, tests/ethercat/test_ethercat_network.py, tests/ethernet/test_ethernet_network.py, tests/test_servo.py
Make the drive setup for the tests more robust.
Fixes # INGK-1062
- Perform a power cycle before loading the firmware file.
=> INGK-1062 Perform a power cycle before loading firmware

ingenialink/configuration_file.py, ingenialink/dictionary.py
Use XMLBase in dictionary.py and configuration_file.py to not duplicate functions
Fixes # INGK-1054
=> INGK-1054 Move XMLBase to dictionary.py and use it to dictionary

Jenkinsfile, pytest.ini, tests/canopen/test_canopen_dictionary_v3.py, tests/conftest.py, tests/eoe/test_eoe_dictionary_v3.py, tests/ethercat/test_ethercat_dictionary_v3.py, tests/ethercat/test_ethercat_examples.py, tests/ethercat/test_pdo.py, tests/test_bitfields.py, tests/test_dictionary.py
Create a new stage for the multislave tests.
Fixes # INGK-1064
- Add a multislave marker to the corresponding tests.
- Create the multislave stage.
- Add a no-connection marker to the tests without markers.
=> INGK-1064 Make sure all drives are operational before running tests

tests/conftest.py
Read the issue for more information.
Fixes # INGK-1074
- Increase the sleep between the power cycle
=> INGK-1074 Increase the sleep between the power cycle

.coveragerc, Jenkinsfile, tox.ini
Since `--import-mode=importlib` pytest adoption, coverage was not working properly. 
The issue was that it was looking for the executed lines of the local repo copy (`--cov=ingenialink`) rather than from the installed package.
Removed `--cov` from `Jenkins` file and added it to `[testenv]` configuration in `tox.ini`.
=> Ingk 1073 coverage is not being reported

CHANGELOG.md, ingenialink/ethercat/network.py, tests/ethercat/test_ethercat_network.py
"_check_node_state" returns a True when called with an empty servos list. This sometimes leads to unhandled exceptions.
Fixes # INGK-1068
=> Ingk 1068 check_node_state return False with empty servo list

tests/test_servo.py
I could not reproduce the failure. Added more info in case of failure.
Fixes # INGK-1055
- Add more info in case of a failure.
=> INGK-1055 Test status word wait change fails sometimes

ingenialink/ethercat/servo.py
The slave object is unreferenced after a disconnection, causing an exception if trying to read/write afterwards. 
Fixes # MOT3-4747
- Raise an exception if the slave has been unreferenced.
Test:
- Follow the steps described in the issue.
- Check that no unhandled exception occurs.
=> MOT3-4747 Raise exception if slave object has been deleted

ingenialink/ethercat/network.py, tests/ethercat/test_ethercat_network.py
Close the EtherCAT master if it was previously not running.
Fixes # INGK-1087
- Close the master in the scan method.
- Close the master in the load_firmware method.
- Add an optional argument to the close_master method. It is used in case the network instance will be used to connect to a servo after the scan or load_firmware method is called.
=> INGK-1087 Close the EtherCAT master if it was previously not running

ingenialink/dictionary.py, tests/ethercat/test_ethercat_dictionary_v3.py, tests/resources/canopen/test_dict_can_v3.0.xdf, tests/resources/canopen/test_dict_can_v3.0_axis.xdf, tests/resources/test_dict_ecat_eoe_safe_v3.0.xdf, tests/resources/test_dict_ecat_eoe_v3.0.xdf
Remove subnode from ECAT/CAN devices in xdf v3. 
=> Remove subnode from ECAT/CAN devices

ingenialink/dictionary.py, tests/canopen/test_canopen_dictionary_v3.py, tests/ethercat/test_ethercat_dictionary_v3.py
Create ECAT register for ECAT device.
=> Ingk 1111 xdf v 3 parser creates can open register instead of ethercat register for ethercat device

ingenialink/ethercat/dictionary.py, ingenialink/ethernet/dictionary.py
Added more information of registers for safety on the hardcoded values of xdf v2. Makes the ingeniamotion fsoe dictionary reader simpler here:
https://github.com/ingeniamc/ingeniamotion/pull/361/files#diff-1322868ebcf8a78a9cd8d609b9883745df286cb31e9dc223971f5d183b538701R527
All registers are from phase I, and are still valid for phase II. For phase II we will not continue to increase these hard coded values.
=> INGM-637 added phase I safety registers to xdfv2

ingenialink/canopen/dictionary.py, ingenialink/canopen/register.py, ingenialink/dictionary.py, ingenialink/ethercat/dictionary.py, ingenialink/ethernet/dictionary.py, ingenialink/ethernet/register.py, ingenialink/register.py, tests/ethercat/test_ethercat_dictionary_v2.py
The hardcoded Monitoring, Safety and PDO registers have some missing or wrong information.
This change relates also to this one:
https://github.com/ingeniamc/ingeniamotion/pull/364
Fixes # INGK-1130
=> Ingk 1130 fix hardcoded registers information

ingenialink/pdo.py, tests/ethercat/test_pdo.py
Needed the integer value of the register mapping value for: https://github.com/ingeniamc/ingeniamotion/pull/366/files
But IL was providing it on bytes only. Since I have not found little usage of it I have moved the conversion to the complete pdo map value calculation, which is the only place where it really does make sense.
Fixes INGM-637
=> INGM-637 change register mapping property to int

Jenkinsfile, tox.ini
The generated wheels could not be uploaded to PyPI due to a metadata error. Update setuptools to avoid this error.
- Update setuptools for wheel generation.
Test:
- Generate wheels using setuptools.
- Upload to internal PyPI successfully.
=> INGK-1134 Update setuptools

.coveragerc, .gitignore, Jenkinsfile, Manifest.in, ingenialink/__init__.py, pyproject.toml, ruff.toml, setup.py, tox.ini
Moved build system to `pyproject.toml` and introduced uploading of development wheels to internal pypi.
-> it is safer to build all wheels since they contain cython code and development wheels may be used for different python versions than the one selected for the Jenkins job run.
Tested that the wheel is uploaded to internal pypi. 
=> INGK-1136 moved build system from setup.py to pyproject.toml and build

ingenialink/pdo.py
Added a method to write the full pdo map value for: https://github.com/ingeniamc/ingeniamotion/pull/373
Pending https://novantamotion.atlassian.net/browse/INGK-1140
There's already a private method on servo that does it, but it private and it does it in two complete access writes instead of one, not sure why and is only called when the pdo does not have an index associated
Fixes INGK-1139
=> INGK-1139 add method to set the pdo map to the slave

ingenialink/ethercat/network.py, tests/ethercat/test_ethercat_network.py
Add pysoem `find_adapters` to scan Ethercat network adapters. 
=> INGM-662 Investigate adapters not appearing if only npcap is selected in adapter configuration

ingenialink/cython_files/get_adapters_addresses.pyx
Fixed `_parse_dns_suffix` parser. 
Changes have been tested adding the following function to `get_adapters_addresses.pyx`:
```
cpdef list[CyFirstDnsSuffix] _test_parse_dns_suffix_with_mock_data():
cdef IP_ADAPTER_DNS_SUFFIX* node1 = <IP_ADAPTER_DNS_SUFFIX*> malloc(sizeof(IP_ADAPTER_DNS_SUFFIX))
cdef IP_ADAPTER_DNS_SUFFIX* node2 = <IP_ADAPTER_DNS_SUFFIX*> malloc(sizeof(IP_ADAPTER_DNS_SUFFIX))
cdef IP_ADAPTER_DNS_SUFFIX* node3 = <IP_ADAPTER_DNS_SUFFIX*> malloc(sizeof(IP_ADAPTER_DNS_SUFFIX))
if not node1 or not node2 or not node3:
if node1: free(node1)
if node2: free(node2)
if node3: free(node3)
raise MemoryError("Failed to allocate test DNS suffix nodes")
test_strings = [
"company.local".encode('utf-16le'),
"example.com".encode('utf-16le'),
"backup.domain.net".encode('utf-16le')
]
cdef …
```
=> INGK-1144 Investigate _parse_dns_suffix error

ingenialink/ethercat/dictionary.py
Minor change to arg name. It did not make sense. PDO Maps are RO or RW
=> fix arg name of EthercatDictionaryV2 pdo maps creation method

Jenkinsfile
To prevent "No space left on device" errors during the Linux stage, virtual environments are now created in a custom directory. This ensures that all data is automatically cleaned up when the Docker image is unmounted, avoiding residual storage issues.
Additionally, test result reporting has been updated to include results for all Python versions.
- Create virtual environments in a custom directory.
- Update test result reporting.
=> INGK-1154 Create linux environments in custom workspace

ingenialink/ethercat/network.py, tests/ethercat/test_ethercat_network.py
This PR enhances the robustness of the firmware loading process over EtherCAT by:
- Adding retry logic when switching a slave to boot state fails.
- Capturing and reporting detailed error messages for each attempt.
- Raising a comprehensive ILFirmwareLoadError if both attempts fail.
- Improving test coverage for these scenarios using mocks.
- Update the load_firmware method.
- Add tests.
=> INGK-1153 FoE fails and returns a boot state not reached

ingenialink/drive_context_manager.py, poetry.lock, pyproject.toml
If the drive is not in preop state, PDOs cannot be written, which would cause drive context manager restore method to fail.
This is a temporary fix to avoid the tests to fail. It will be reworked in https://novantamotion.atlassian.net/browse/INGK-1160.
=> Fix drive context manager pre-op error

ingenialink/ethercat/network.py, ingenialink/ethercat/servo.py, tests/conftest.py, tests/ethercat/mock.py, tests/ethercat/test_ethercat_network.py
Config Init in soem is though to be an initialization function that is called once during master configuration.
However, there several cases while a "connected" servo is on the network and a config_init is done.
- Stopping PDOS. This one is questionable. I have created INGK-1162 as related.
- Recovering from a disconnection. Not sure if is questionable, can help recover from weird master states.
Either way this produced a situation where the object reference CDefSlave servos were using was outdated. Since the pointer to the object is the same it kind of worked but was wrong. Additionally this cython object holds the callbacks of emergency, so those were definitely missing.
Fixes INGK-1122
Please describe the tests that you …
=> Ingk 1122 c def slave is not updated on config init

Jenkinsfile
Nightlies already trigger builds with all versions of python. Testing stages take 60 minutes of each machine time, which is very valuable during the day.
Develop builds that are triggered by scans should take the same as PR builds (15 min),
This pattern is already implemented on IM
Fixes INGK-1163
N/A
=> INGK-1163 do not run all python versions on develop index scans

Jenkinsfile
Jenkins fixes for different python versions.
Right now all the docker environment activations are supposed to run with the default python version, which is the minimum one. However, since the python version can be selected, the maximum one may run, leading to an error:
http://jenkins.ingenia/job/Novanta%20Motion%20-%20Ingenia%20-%20Git/job/ingenialink-python/job/develop/702/  
=> Ingk 1167 fix jenkins for python 3 9

Jenkinsfile
Error introduced in https://github.com/ingeniamc/ingenialink-python/pull/624 when trying to fix develop to work with all python versions. If a parameter is specified in the cron, `parameterizedCron` should be used.
=> Fix jenkins cron

ingenialink/csv_configuration_file.py, ingenialink/ethercat/servo.py, tests/test_csv_configuration_file.py
Export values to CSV using big-endian format.
- Add the __format_value_for_csv method.
- Add test.
=> INGK-1181 Export values using big endian format

ingenialink/canopen/network.py, ingenialink/ethercat/network.py, ingenialink/ethernet/network.py
The disconnection notification is being done too early, causing the callback method to be called before INGK is finished with the connection teardown.
- Notify of the disconnection after the teardown is finished.
=> INGK-1184 Notify disconnection after teardown is finished

ingenialink/canopen/dictionary.py, ingenialink/dictionary.py, ingenialink/drive_context_manager.py, ingenialink/ethercat/dictionary.py, ingenialink/ethernet/dictionary.py, ingenialink/servo.py, ingenialink/utils/_utils.py, poetry.lock, pyproject.toml, tests/test_drive_context_manager.py
Add callback function for complete access read/write.
Tested with https://github.com/ingeniamc/ingeniamotion/pull/433 and summit-testing-framework new wheel including the INGK changes introduced by this PR.
=> Ingk 1161 callback function for complete access
