- ingenialink/registers.py
"internal_use" property added to registers
> SWLIB-103 internal_use property added to registers

- examples/general/load_save_config.py
- examples/general/monitoring.py
- examples/general/slave_connection.py
- examples/general/summit.xml
Slave connection, Load and Save configuration files and Monitoring examples added
> SWLIB-127 Examples added

- ingenialink/canopen/servo_node.py
Modified node property to be public in the Servo class
> Modified node property to be public in the Servo class

- ingenialink/canopen/servo_node.py
Cast the argument data in raw write function for incoming float and strings
> Cast the argument data in raw write function

- ingenialink/canopen/dictionary.py
- ingenialink/canopen/net.py
- ingenialink/canopen/registers.py
- ingenialink/canopen/servo_node.py
Added support for ML3 Wizard configurator tests and match dictionary structures and used functions.
> Added support for ML3 Wizard configurator tests

- ingenialink/canopen/dictionary.py
- ingenialink/canopen/servo_node.py
Added dictionary version as public property and updated registers uid for class Register initializations
> Updated registers uid for class Register initializations

- ingenialink/canopen/servo_node.py
Fixed permission error trying to read a file in permission restricted location when loading config
> Fixed permission error trying to read a file on load

- ingenialink/canopen/servo_node.py
Added subnode to all needed functions to target the proper subnodes
> Added subnode to all needed functions

- ingenialink/canopen/net.py
Connect through node and channels
> Added manual connection through nodes for canopen

- ingenialink/canopen/net.py
- ingenialink/canopen/servo_node.py
Implemented detect nodes to support new connection methods
> Canopen multiaxis

- ingenialink/canopen/net.py
Added logs for each connection fail
> Added log errors for connection fails

- ingenialink/servo.py
Function created to reload all the dictionary errors.
> Function created to reload all the dictionary errors.

- .github/pull_request_template.md
> INGK-549 Create pull_request_template.md

- ingenialink/dictionary.py
- ingenialink/servo.py
- tests/servo/test_servo.py
This PR updates the `save_configuration` function so the xcf file is created based on the registers stored at the dictionary. It also improves the test related to this function so not only checks if the file exists.
> INGK-520 Update save_configuration function

- test_lib.sh
This PR adds a bash script that runs all tests for all protocols and combines the reports.
Fixes # INGK-566
> INGK-566 Add a bash script to run all the tests and combine reports

- .github/pull_request_template.md
- Jenkinsfile
- docs/conf.py
- requirements/dev-requirements.txt
- setup.py
This PR implements a formatting check at CI using black.
Fixes # INGK-565
> INGK-565 Black formatting

- ingenialink/ingenialink_build.py
- requirements/dev-requirements.txt
This PR reverts the changes of #261
> INGK-587 Upgrade black

- ingenialink/eoe/network.py
The EoE service must be started manually after the drives have been configured. This is because the feature to stop the service is not yet implemented.
> INGK-540 Add multi slave support

- ingenialink/eoe/network.py
The changes from [INGK-540](https://github.com/ingeniamc/ingenialink-python/pull/230) did not go into develop. Opening a new PR to incorporate these changes to develop.
[INGK-540]: https://ingeniamc.atlassian.net/browse/INGK-540?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> INGK-533 Interface network class soem service

- requirements/requirements.txt
- setup.py
Remove NumPy from requirements as it is no longer used by the library.
Fixes # INGK-601
> INGK-601 Remove numpy from requirements

- CHANGELOG.md
> Release 7.0.3

- Jenkinsfile
- ingenialink/canopen/dictionary.py
- ingenialink/canopen/network.py
- ingenialink/canopen/register.py
- ingenialink/canopen/servo.py
- ingenialink/dictionary.py
- ingenialink/eoe/network.py
- ingenialink/ethercat/network.py
- ingenialink/ethernet/dictionary.py
- ingenialink/ethernet/network.py
- ingenialink/ethernet/register.py
- ingenialink/ethernet/servo.py
- ingenialink/network.py
- ingenialink/poller.py
- ingenialink/register.py
- ingenialink/servo.py
- ingenialink/utils/_utils.py
- ingenialink/utils/mcb.py
- ingenialink/utils/udp.py
- ingenialink/virtual/virtual_drive.py
- mypy.ini
- requirements/dev-requirements.txt
- setup.py
- tests/canopen/test_canopen_register.py
- tests/ethernet/test_ethernet_register.py
- tests/test_register.py
- tests/test_servo.py
- tests/test_virtual_drive.py
This PR add type hints and mypy checking.
Fixes # 631
> INGK-631 Add mypy

- CHANGELOG.md
- setup.py
> INGK-682 Add PySOEM to setup

- CHANGELOG.md
- ingenialink/poller.py
- Fix acquisiton data variable initialization
- Create a poller and check that if does not hang.
> INGK-685 Fix acquisiton data variable initialization

- tests/ethercat/test_ethercat_register.py
Remove unexisting imports
Fixes #INGK-686
> INGK-686 Remove unexisting imports

- ingenialink/ethercat/network.py
- ingenialink/ethercat/servo.py
- mypy.ini
Raise an exception if an emergency message is received.
Fixes #INGK-729
- Add the _get_emergency_description function
> INGK-729 Handle EMCY messages

- CHANGELOG.md
- ingenialink/virtual/virtual_drive.py
- tests/test_virtual_drive.py
> INGK-758 Implement motor enable and disable in the virtual drive

- ingenialink/virtual/resources/virtual_drive.xcf
- ingenialink/virtual/virtual_drive.py
- tests/test_virtual_drive.py
This PR includes an emulator of the feedback tests.
Fixes # INGK-649
> INGK-649 Emulate feedback tests in the virtual drive

- ingenialink/canopen/register.py
- ingenialink/dictionary.py
- ingenialink/ethernet/register.py
- ingenialink/register.py
- tests/canopen/test_canopen_register.py
- tests/ethercat/test_ethercat_register.py
- tests/ethernet/test_ethernet_register.py
- tests/test_register.py
- virtual_drive/core.py
This PR switches keys and values in the enums
Fixes # INGK-787
> INGK-787 Switch keys and values in enums

- tests/ethercat/test_pdo.py
- tox.ini
- virtual_drive/core.py
This PR fixes the typing of the virtual drive.
Fixes # INGK-838 
> INGK-838 Fix typing of the virtual drive

- ingenialink/virtual/dictionary.py
- tests/virtual/test_virtual_dictionary.py
- virtual_drive/core.py
This PR fixes the issue when running the virtual drive with custom diccionaries.
Fixes # INGK-840
> INGK-840 Fix virtual drive with custom dictionaries

- CHANGELOG.md
- ingenialink/canopen/network.py
- ingenialink/utils/_utils.py
Supress IXXAT missing DLLs logs
Fixes # INGK-863
- Create Context Manager to disable logs.
- Supress IXXAT missing DLLs logs.
Test:
- Uninstall IXXAT drives
- Import ingenialink
- Check that the missing DLLs logs are not shown.
> INGK-863 Supress IXXAT missing DLLs logs

- ingenialink/canopen/network.py
Create connection arguments upon instantiation
Fixes # INGK-883
> INGK-883 Create connection arguments upon instantiation

- ingenialink/__init__.py
- ingenialink/canopen/dictionary.py
- ingenialink/canopen/network.py
- ingenialink/canopen/register.py
- ingenialink/canopen/servo.py
- ingenialink/constants.py
- ingenialink/dictionary.py
- ingenialink/ethercat/dictionary.py
- ingenialink/ethercat/network.py
- ingenialink/ethercat/register.py
- ingenialink/ethercat/servo.py
- ingenialink/ethernet/dictionary.py
- ingenialink/ethernet/network.py
- ingenialink/ethernet/register.py
- ingenialink/ethernet/servo.py
- ingenialink/pdo.py
- ingenialink/poller.py
- ingenialink/register.py
- ingenialink/servo.py
- ingenialink/utils/_utils.py
- ingenialink/utils/mcb.py
- ingenialink/utils/udp.py
- pyproject.toml
- ruff.toml
- tests/test_dictionary.py
- tox.ini
Add ruff for code formatting and linter.
Fixes # INGK-876
- Remove black from the project.
- Add ruff as a code formatter and linter.
- Fix ruff errors.
- Add Jenkins stage for checking errors.
> INGK-876 Add ruff

- .github/pull_request_template.md
Update PR template
Fixes # INGK-879
> INGK-879 Update PR template

- ingenialink/canopen/network.py
Move the program state machine to the start state after a failure sending the firmware file.
Fixes # INGK-891
- Add the __send_fw_file_failure method.
- Connect to ML3
- Load an incorrect firmware file. It will fail.
- Load a correct firmware file. It will succeed.
> INGK-891 Move the program state machine to the start state

- CHANGELOG.md
- ingenialink/poller.py
In this PR the sampling precision of the Poller is fixed. For instance, using the EoE service:
Fixes # INGK-900
> INGK-900 Improve polling sampling precision

- tests/test_servo.py
> INGK-803 Remove skip mark in the test_save_configuration

- tests/config.json
- tests/test_servo.py
Please include a summary of the change and which issue is fixed. 
Fixes # INGK-913
> INGK-913 Test ethernet only on Everest

- pytest.ini
- tests/canopen/test_canopen_register.py
- tests/ethercat/test_ethercat_register.py
- tests/ethernet/test_ethernet_register.py
Fixes # INGK-567
Please describe the tests that you ran to verify your changes if it applies.
> INGK-567 Remove smoke mark

- Jenkinsfile
> INGK-903 Avoid cloning the repository in Jenkins

- Jenkinsfile
Publish pytest results even if tests fail.
Fixes # INGK-805
- Update Jenkinsfile.
> INGK-805 Publish pytest results even if tests fail

- Jenkinsfile
Skip the EtherCAT tests while the ECAT machine is under maintenance.
Fixes # INGK-926
> INGK-926 Skip EtherCAT tests

- ingenialink/canopen/network.py
- ingenialink/ethercat/network.py
- ingenialink/ethernet/network.py
- ingenialink/servo.py
- mypy.ini
- tox.ini
Upgrade the mypy version.
Fixes # INGK-806
- Update tox environment.
- Fix mypy errors.
- Run mypy check.
- Check no errors are found.
> INGK-806 Update mypy version

- docs/api.rst
- docs/api/base_classes.rst
- docs/api/protocols.rst
- tox.ini
In this PR, the sphinx version is updated.
Fixes # INGK-800
> INGK-800 Update sphinx version

- CHANGELOG.md
- examples/canopen/can_connection.py
- examples/canopen/can_connection_linux.py
- examples/canopen/can_disturbance.py
- examples/canopen/can_load_firmware.py
- examples/canopen/can_load_save_config.py
- examples/canopen/can_monitoring.py
- examples/canopen/can_store_restore.py
- examples/ethercat/ecat_connection.py
- examples/ethercat/ecat_load_firmware.py
- examples/ethercat/process_data_objects.py
- examples/ethernet/eth_connection.py
- examples/ethernet/eth_load_firmware.py
- examples/ethernet/eth_load_save_config.py
- examples/ethernet/eth_monitoring.py
- examples/ethernet/eth_store_restore.py
- tests/canopen/test_canopen_examples.py
- tests/ethercat/test_ethercat_examples.py
- tests/ethercat/test_pdo.py
- tests/ethernet/test_ethernet_examples.py
In this PR, tests for the examples are added.
Fixes # INGK-689
> INGK-689 Add tests for the examples

- Jenkinsfile
- tests/config.json
Run the EtherCAT tests.
Fixes # INGK-930
- Update Jenkinsfile
> INGK-930 Remove skip

- ingenialink/canopen/network.py
Remove unused attributes and method in the canopen network class.
> INGK-890 Clean the canopen network class

- CHANGELOG.md
- examples/canopen/can_connection.py
- examples/canopen/can_disturbance.py
- examples/canopen/can_load_firmware.py
- examples/canopen/can_load_save_config.py
- examples/canopen/can_monitoring.py
- examples/canopen/can_store_restore.py
- examples/ethercat/ecat_connection.py
- examples/ethercat/ecat_load_firmware.py
- examples/ethercat/process_data_objects.py
- examples/ethernet/eth_connection.py
- examples/ethernet/eth_load_firmware.py
- examples/ethernet/eth_load_save_config.py
- examples/ethernet/eth_monitoring.py
- examples/ethernet/eth_store_restore.py
- ingenialink/ethercat/network.py
- mypy.ini
- tox.ini
Add type checking to all the files in the example-folder.
The tox type check (Jenkins) will also check these files now.
[Issue](https://novantamotion.atlassian.net/browse/INGK-804)
> INGK-804 add typing to examples

- CHANGELOG.md
- examples/canopen/can_monitoring.py
- examples/ethernet/eth_monitoring.py
- ingenialink/ethercat/network.py
- tests/config.json
Add an optional password for the FOE bootloader
Fixes # INGK-934
- Add an optional password for the FOE bootloader
- Load firmware without setting a password.
- Check that the firmware loading process is successful.
- Load firmware using a custom password.
- Check that the firmware loading process fails.
> INGK-934 Add an optional password for the FOE bootloader

- CHANGELOG.md
- ingenialink/dictionary.py
- tests/test_dictionary.py
Add the coco product code attribute.
Fixes # INGK-950
- Add the coco product code attribute
> INGK-950 Add the coco product code attribute

- CHANGELOG.md
- ingenialink/exceptions.py
- ingenialink/utils/mcb.py
- tests/test_mcb.py
Add nack error code as a property
Fixes INGK-398
-  add test of formatting message
-  store error code on exception
> INGK-398 Add nack error code as a property

- tests/config.json
- tests/conftest.py
- tests/test_servo.py
Properly test the store/restore functionalities by incorporating a power cycle.
Fixes # INGK-573
> INGK-573 Implement a function to do a power cycle by software if possible

- CHANGELOG.md
- ingenialink/ethercat/network.py
Update RPDO values before send process data
Fixes # INGK-964
> INGK-964 Update RPDO values before send process data

- README.rst
Add branch status and Python version badges.
> INGK-354 Add branch status and python version badges

- Jenkinsfile
- tests/canopen/test_canopen_network.py
- tests/config.json
- tests/conftest.py
- tests/ethercat/test_ethercat_network.py
- tests/test_servo.py
- tox.ini
Run tests using all the available drives in the rack.
Fixes # INGK-644
- Improve Jenkins pipeline.
- Use EVE-XCR for CANopen and EtherCAT tests.
- Fix tests
> INGK-644 Test on all drives

- ingenialink/ethercat/servo.py
Improve PySOEM error description
Fixes # INGK-973
> INGK-973 Improve PySOEM error description

- ingenialink/ethercat/network.py
Remove the PySOEM [error ](https://github.com/bnjmnp/pysoem/commit/2680b42edcec1c95545c97f40827723b0754582b#diff-865d862671054fb3e4beeb586d6c54189e1ac6c56e8ed4ee3e42beea972b7d86L204)patch.
Fixes # INGK-977
> INGM-977 Remove patch

- tests/canopen/test_canopen_examples.py
- tests/ethercat/test_ethercat_examples.py
- tests/ethernet/test_ethernet_examples.py
- Remove script runner deprecation warning
> INGK-956 Remove script runner deprecation warning

- ingenialink/canopen/network.py
- ingenialink/ethercat/network.py
- ingenialink/ethernet/network.py
- ingenialink/network.py
- tests/ethernet/test_ethernet_network.py
- tests/virtual/test_virtual_network.py
- Define the servo network state setter/getter in the base class.
- Make the getter public.
> INGK-994 Define the servo network state setter/getter in the base class

- ingenialink/canopen/dictionary.py
- ingenialink/dictionary.py
- ingenialink/ethercat/dictionary.py
- ingenialink/ethernet/dictionary.py
- tests/test_dictionary.py
- Make dictionary constants private
> INGK-992 Make dictionary constants private

- ingenialink/canopen/network.py
> INGK-954 Fix log message

- ingenialink/servo.py
> INGK-967 Add error message

- ingenialink/register.py
- tests/test_register.py
> INGK-997 Simplify and fix register range method

- .github/pull_request_template.md
- tests/canopen/test_canopen_dictionary_v2.py
- tests/canopen/test_canopen_dictionary_v3.py
- tests/canopen/test_canopen_network.py
- tests/canopen/test_canopen_register.py
- tests/canopen/test_canopen_servo.py
- tests/eoe/test_eoe_dictionary_v3.py
- tests/eoe/test_eoe_network.py
- tests/ethercat/test_ethercat_dictionary_v3.py
- tests/ethercat/test_ethercat_network.py
- tests/ethernet/test_ethernet_dictionary_v2.py
- tests/ethernet/test_ethernet_register.py
- tests/test_dictionary.py
- tests/test_mcb.py
- tests/test_register.py
- tests/test_servo.py
- tests/test_utils.py
- tox.ini
- Include the test folder on the formatting and linting stage.
- Fix ruff errors.
- Update PR template.
> INGK-1000 Include formatting and linting on tests

- tests/config.json
- tests/test_register.py
- Use the pool server to retrieve config files.
> INGK-1002 Use the pool server

- tests/test_servo.py
- Simplify the test_load_configuration test
- Fix the test_load_configuration test
> INGK-1004 Fix test

- ingenialink/canopen/network.py
- ingenialink/canopen/servo.py
- ingenialink/ethercat/servo.py
- ingenialink/exceptions.py
- ingenialink/servo.py
- Remove unused exceptions.
- Remove unnecessary exception (ILObjectNotExist).
> INGK-966 Remove unnecessary exceptions in ingenialink

- CHANGELOG.md
- ingenialink/ethernet/servo.py
- Add the get_mac_address and set_mac_address methods.
- Update the change_tcp_ip_parameters method to accept a MAC address.
> INGK-1006 Add a method to set the MAC Address

- ingenialink/bitfield.py
- ingenialink/dictionary.py
- tests/canopen/test_canopen_dictionary_v3.py
- tests/eoe/test_eoe_dictionary_v3.py
- tests/ethercat/test_ethercat_dictionary_v3.py
- tests/resources/canopen/test_dict_can_v3.0.xdf
- tests/resources/test_dict_ecat_eoe_v3.0.xdf
Pending work from https://github.com/ingeniamc/ingenialink-python/pull/493
Fixes INGK-1005
> Ingk 1005 add bitfield information on dictionaries v 3

- Jenkinsfile
Add nightly builds
Fixes # INGK-1011
- Add cron settings in Jenkinsfile
> INGK-1011 Add nightly builds

- Jenkinsfile
Migrated publish of files to new function and moved the section after the docker build. Test will be executed later
> Cit 296 evaluate using scp for publishing to distext

- Jenkinsfile
Use the latest CICD lib version.
> INGK-1029 Update CICD lib version

- ingenialink/canopen/network.py
- tests/test_virtual_drive.py
- virtual_drive/core.py
Fix ruff errors after the mypy config changes.
Fixes # INGK-1045
> INGK-1045 Fix ruff errors

- CHANGELOG.md
- ingenialink/eoe/network.py
- ingenialink/ethernet/network.py
- ingenialink/network.py
- mypy.ini
- setup.py
- tests/ethernet/test_ethernet_network.py
Implement Ethernet scan.
Fixes # INGK-1042
- Implement the scan_slave method.
- Implement the scan_slaves_info method.
> INGK-1042 Implement Ethernet scan

- CHANGELOG.md
- docs/api/base_classes/configuration_file.rst
- ingenialink/canopen/servo.py
- ingenialink/configuration_file.py
- ingenialink/exceptions.py
- ingenialink/servo.py
- tests/test_configuration_file.py
- tests/test_servo.py
- virtual_drive/core.py
Create a class to read and write XCF file
Fixes # Ingk-990
> Ingk 990 implement xcf v3

- ingenialink/ethernet/network.py
COMOCO drives can fail to respond to the first ping request. Always retry a second time.
Fixes # INGK-1059
- Perform two rounds of ping scan.
- Decrease the scan connection timeout.
> INGK-1059 Perform ping sweep twice

- ingenialink/ethercat/network.py
The EtherCAT slave can take some time to become operational after the firmware file is loaded.
Fixes # INGK-1060
- Add a waiting mechanism after the firmware loading process.
> INGK-1060 Wait for a drive to become operational after loading firmware

- examples/ethernet/eth_monitoring.py
- ingenialink/servo.py
Remove unused legacy argument
Fixes # INGK-1036
- Remove legacy argument.
> INGK-1036 Remove legacy argument

- Jenkinsfile
Jenkinsfile fixes to properly find the wheel in ingeniamotion. 
> Jenkinsfile fixes - use custom ingenialink wheel

- ingenialink/ethercat/network.py
The FoE write operation can fail occasionally. A retry mechanism is added to recover from this.
Fixes # INGK-1065
- Add a retry mechanism to the EtherCAT load firmware method.
**Test 1:**
- Force a failure on the first iteration of the loading firmware process (by unplugging the cable).
- Check that the firmware process is successful on the second iteration.
**Test 2:**
- Load a firmware file.
- Check that the firmware process is successful on the first iteration.
> INGK-1065 Add a retry mechanism

- ingenialink/bitfield.py
- ingenialink/canopen/network.py
- ingenialink/dictionary.py
- ingenialink/emcy.py
- ingenialink/utils/_utils.py
- ruff.toml
- tests/ethercat/test_ethercat_examples.py
- tests/ethernet/test_ethernet_network.py
- virtual_drive/core.py
> INGK-1069: Use ruff preview to use DOC rule

- tests/conftest.py
- tests/test_servo.py
Check the issue for more information.
Fixes # INGK-1075
- Increase the sleep between the power cycle.
> INGK-1075 Increase the sleep time between the power cycle

- ingenialink/servo.py
> Add safety uids

- virtual_drive/core.py
- virtual_drive/resources/virtual_drive.xcf
- virtual_drive/resources/virtual_drive.xdf
Simulate SinCos encoder behavior in the virtual drive.
Fixes # INGK-1077
- Simulate SinCos feedback test.
- Simulate SinCos raw signals.
> INGK-1077 Simulate SinCos encoder feedback test

- virtual_drive/resources/virtual_drive.xdf
Add gain and offsets SinCos registers.
Fixes # INGK-1083
> INGK-1083 Add gain and offsets SinCos registers

- ingenialink/ethernet/dictionary.py
Add safety support for ethernet
> INGK-1080-safety-modules-accesses-in-ethernet

- tests/config.json
- tests/conftest.py
Use the revision number to indicate the firmware file to be loaded.
Fixes #INGK-1086
- Replace the firmware file path with the revision number.
> INGK-1086 Use the revision number to load firmware

- ingenialink/drive_context_manager.py
- tests/test_drive_context_manager.py
Drive context manager to rollback the changes in drive registers that the tests may perform.
It has been created as a context, but it can also be used as a fixture.
> Drive context manager

- Jenkinsfile
Stash all the generated wheels.
Fixes # INGK-1093
- Update Jenkinsfile.
- [] Run tests.
> INGK-1093 Stash all wheels

- Jenkinsfile
Add 1 hour timeout to hardware testing stage.
> Cit 382 add timeouts to testing stages

- Jenkinsfile
Add timestamps to Jenkins logs.
Fixes #INGK-1120
> INGK-1120-add-timestamp-to-jenkins-logs

- .gitignore
- Jenkinsfile
> Fix tox python version

- Jenkinsfile
- poetry.lock
- pyproject.toml
> Update summit testing framework

- ingenialink/canopen/dictionary.py
- ingenialink/canopen/register.py
- ingenialink/dictionary.py
- ingenialink/drive_context_manager.py
- ingenialink/ethercat/dictionary.py
Add Canopen object reference to Canopen/EtherCAT registers. 
> Ingk 1161 proposal

- ingenialink/dictionary.py
- ingenialink/drive_context_manager.py
- ingenialink/ethercat/dictionary.py
- tests/canopen/test_canopen_dictionary_v2.py
- tests/canopen/test_canopen_dictionary_v3.py
- tests/ethercat/test_ethercat_dictionary_v2.py
- tests/ethercat/test_ethercat_dictionary_v3.py
- tests/test_dictionary.py
Fix missing canopen objects and object reference in register.  
> INGK-1197 fix canopen objects
